title: My board (name suggestions?)
hero_image: images/banner.png
description: Make a webpage that's a collection of your favourite things
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your page
  - title: Your grid
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
